version: '3.3'

services:  
  mongo:
    image: mongo:latest
    container_name: mongo
    # volumes:
    # - .data/mdata:/data/db
    ports:
     - "27017:27017"
    command: mongod --port 27017 --bind_ip 0.0.0.0

  server:
    build: server/
    image: server
    container_name: server
    ports:
      - '5000:5000'
    volumes:
      - .:/users
    depends_on:
      - mongo
    environment:
      - DEBUG=1 # 1/0
      - COUNT_USERS=100 # int
      - GENDER=male # male/female

  client:
    build: client/
    image: client
    container_name: client
    volumes:
      - ./client
    ports:
      - '5001:5001'
    depends_on:
      - server
    environment:
      - DEBUG=1
