version: '3.3'

services:  
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
     - "27017:27017"

  server:
    build: server/
    image: server
    container_name: server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/server
    depends_on:
      - mongo
    environment:
      - DEBUG=1 # 1/0
      - COUNT_USERS=100 # int
      - GENDER=male # male/female

  client:
    build: client/
    image: client
    container_name: client
    volumes:
      - ./client:/client/
    ports:
      - '5001:5001'
    depends_on:
      - server
    environment:
      - DEBUG=1

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    # volumes:
    #   - client:/etc/nginx/client/static/
    volumes:
      - ./nginx/conf.d/Flask_API.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
